app = "blockesdefender-bot"

[build]
  builder = "paketobuildpacks/builder:base"

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 256

[env]
  TELEGRAM_BOT_TOKEN = "8033171833:AAGXaHFnFmi0Pv-R9M1qZ6IK0cittDx0cYU"

[[http_service]]
  internal_port = 8080
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 0
